vich_uploader:
    db_driver: orm
    mappings:
        trick_images:
            uri_prefix: /uploads/tricks/images
            upload_destination: '%kernel.project_dir%/public/uploads/tricks/images'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
