parameters:
    trick_images_directory: '%kernel.project_dir%/public/uploads/tricks/images'
    user_images_directory: '%kernel.project_dir%/public/uploads/users'


services:
    App\EventListener\VideoSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Validator\:
        resource: '../src/Validator'
        tags: ['validator.constraint_validator']
        public: true


framework:
    secret: '%env(APP_SECRET)%'
